[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "forge-std/=lib/forge-std/src/",
  "diamond-2-hardhat/=lib/diamond-2-hardhat/contracts/",
  "openzeppelin/=lib/openzeppelin-contracts/contracts/",
  'solidity-bytes-utils/=lib/solidity-bytes-utils/',
  '@layerzerolabs/lz-evm-protocol-v2/=node_modules/@layerzerolabs/lz-evm-protocol-v2/',
  '@layerzerolabs/lz-evm-messagelib-v2/=node_modules/@layerzerolabs/lz-evm-messagelib-v2/',
  '@layerzerolabs/lz-evm-v1-0.7/=node_modules/@layerzerolabs/lz-evm-v1-0.7/',
]
cache = true
force = false
evm_version = 'paris'
auto_detect_solc = true
offline = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
mainnet = "${ETH_MAINNET_RPC_URL}"
sepolia = "${ETH_SEPOLIA_RPC_URL}"
base = "${BASE_MAINNET_RPC_URL}"
bases = "${BASE_SEPOLIA_RPC_URL}"
anvil = "${LOCAL_RPC_URL}"
aurora = "${AURORA_MAINNET_RPC_URL}"
aurora_testnet = "${AURORA_TESTNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
