name: Tests

on: push

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      
      - name: Install dependencies
        run: bun i

      - name: Compile
        run: bun compile --sizes
        id: build

      - name: Run tests
        run: bun test
        id: test
